name: clocka
description: A basic alarm clock app built with Flutter.
version: 1.1.1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  flutter_local_notifications: ^17.2.1
  provider: ^6.0.3
  font_awesome_flutter: ^10.0.0
  shared_preferences: ^2.0.10
  android_alarm_manager_plus: ^2.0.6
  flutter_launcher_icons: ^0.9.2
  simple_ripple_animation: ^0.0.9
  clock: ^1.1.0 # Add this line to include the clock package


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true